# Generated by Django 5.2.6 on 2025-09-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'room', 'song_id')},
        ),
    ]
